/* AUTOGENERATED-STYLE FILE. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

#include "config.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_fragmented_then_oversized_input_does_not_overflow(void);
extern void test_oversized_input_without_sync_is_ignored(void);

char const *progname;

//=======MAIN=====
int main(int argc, char *argv[])
{
  (void)argc;
  progname = argv[0];

  UnityBegin("t-refclock_zyfer.c");
  RUN_TEST(test_fragmented_then_oversized_input_does_not_overflow, 1);
  RUN_TEST(test_oversized_input_without_sync_is_ignored, 1);

  return (UnityEnd());
}
